version: "3"
services:
  redis:
    image: redis:latest
    volumes:
      - sgb-redis-data:/data
  slack_greet_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file: .env
volumes:
  sgb-redis-data: